<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jacob Van Vleet">
<meta name="dcterms.date" content="2026-08-01">

<title>Transportation Habits, Age, and Communication Apprehension</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="GroupManu_files/libs/clipboard/clipboard.min.js"></script>
<script src="GroupManu_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="GroupManu_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="GroupManu_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="GroupManu_files/libs/quarto-html/popper.min.js"></script>
<script src="GroupManu_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GroupManu_files/libs/quarto-html/anchor.min.js"></script>
<link href="GroupManu_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GroupManu_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GroupManu_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GroupManu_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GroupManu_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation"><span class="header-section-number">2</span> Data Preparation</a>
  <ul class="collapse">
  <li><a href="#data-collection-and-merging" id="toc-data-collection-and-merging" class="nav-link" data-scroll-target="#data-collection-and-merging"><span class="header-section-number">2.1</span> Data Collection and Merging</a></li>
  <li><a href="#variable-coding-and-creation" id="toc-variable-coding-and-creation" class="nav-link" data-scroll-target="#variable-coding-and-creation"><span class="header-section-number">2.2</span> Variable Coding and Creation</a></li>
  </ul></li>
  <li><a href="#transportation-habits-and-communication-apprehension" id="toc-transportation-habits-and-communication-apprehension" class="nav-link" data-scroll-target="#transportation-habits-and-communication-apprehension"><span class="header-section-number">3</span> Transportation Habits and Communication Apprehension</a>
  <ul class="collapse">
  <li><a href="#transportation-mode-differences" id="toc-transportation-mode-differences" class="nav-link" data-scroll-target="#transportation-mode-differences"><span class="header-section-number">3.1</span> Transportation Mode Differences</a></li>
  <li><a href="#transportation-frequency-effects" id="toc-transportation-frequency-effects" class="nav-link" data-scroll-target="#transportation-frequency-effects"><span class="header-section-number">3.2</span> Transportation Frequency Effects</a></li>
  </ul></li>
  <li><a href="#age-and-communication-apprehension" id="toc-age-and-communication-apprehension" class="nav-link" data-scroll-target="#age-and-communication-apprehension"><span class="header-section-number">4</span> Age and Communication Apprehension</a></li>
  <li><a href="#interaction-between-transportation-use-and-age" id="toc-interaction-between-transportation-use-and-age" class="nav-link" data-scroll-target="#interaction-between-transportation-use-and-age"><span class="header-section-number">5</span> Interaction Between Transportation Use and Age</a>
  <ul class="collapse">
  <li><a href="#age-group-moderation-analysis" id="toc-age-group-moderation-analysis" class="nav-link" data-scroll-target="#age-group-moderation-analysis"><span class="header-section-number">5.1</span> Age Group Moderation Analysis</a></li>
  </ul></li>
  <li><a href="#predictive-modeling" id="toc-predictive-modeling" class="nav-link" data-scroll-target="#predictive-modeling"><span class="header-section-number">6</span> Predictive Modeling</a>
  <ul class="collapse">
  <li><a href="#baseline-model" id="toc-baseline-model" class="nav-link" data-scroll-target="#baseline-model"><span class="header-section-number">6.1</span> Baseline Model</a></li>
  <li><a href="#k-nearest-neighbors-knn" id="toc-k-nearest-neighbors-knn" class="nav-link" data-scroll-target="#k-nearest-neighbors-knn"><span class="header-section-number">6.2</span> K-Nearest Neighbors (KNN)</a></li>
  <li><a href="#random-forest" id="toc-random-forest" class="nav-link" data-scroll-target="#random-forest"><span class="header-section-number">6.3</span> Random Forest</a></li>
  <li><a href="#neural-networks" id="toc-neural-networks" class="nav-link" data-scroll-target="#neural-networks"><span class="header-section-number">6.4</span> Neural Networks</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">6.5</span> Model Comparison</a></li>
  <li><a href="#prediction-accuracy-visualizations" id="toc-prediction-accuracy-visualizations" class="nav-link" data-scroll-target="#prediction-accuracy-visualizations"><span class="header-section-number">6.6</span> Prediction Accuracy Visualizations</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#remaining-questions" id="toc-remaining-questions" class="nav-link" data-scroll-target="#remaining-questions"><span class="header-section-number">7.1</span> Remaining Questions</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Transportation Habits, Age, and Communication Apprehension</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jacob Van Vleet </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Communication apprehension—the fear or anxiety associated with real or anticipated communication with others—has been studied extensively in relation to various individual differences and contextual factors. This study examines whether transportation habits and age are associated with communication apprehension. Specifically, we investigate whether individuals who use different modes of transportation (ride-share services vs.&nbsp;public transportation) differ in their communication apprehension levels, and whether age predicts communication apprehension. Understanding these relationships may provide insights into how daily behaviors and demographic characteristics relate to communication patterns.</p>
</section>
<section id="data-preparation" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data Preparation</h1>
<section id="data-collection-and-merging" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-collection-and-merging"><span class="header-section-number">2.1</span> Data Collection and Merging</h2>
<p>Data were collected from participants who completed a survey assessing communication apprehension and transportation habits. The original data were stored in three separate files: <code>PRCAProlificExport_FileA.csv</code>, <code>PRCAProlificExport_FileB.csv</code>, and <code>PRCAQualtricsExport_FileC.csv</code>. The two Prolific files (<code>FileA</code> and <code>FileB</code>) contained participant demographic information including age, sex, country of residence, student status, and employment status. The Qualtrics file (<code>FileC</code>) contained survey responses including communication apprehension questions and transportation usage patterns.</p>
<p>The data cleaning process involved several steps. First, the two Prolific files were concatenated using Python’s pandas library, resulting in a combined dataset with duplicate participant IDs removed (keeping the first occurrence). This yielded 252 unique participants. The combined Prolific data were then merged with the Qualtrics data by matching the <code>Q0</code> column in the Qualtrics file with the <code>Participant id</code> column in the Prolific file. This merge was performed using a left join, and rows without matches (n = 31) were filtered out, resulting in a final dataset of 252 participants with complete demographic and survey data.</p>
</section>
<section id="variable-coding-and-creation" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variable-coding-and-creation"><span class="header-section-number">2.2</span> Variable Coding and Creation</h2>
<p>After merging, the survey responses required coding to create numeric variables for analysis. Likert-scale responses to communication apprehension questions were reverse-coded where appropriate. Questions Q1, Q3, Q5, Q13, Q15, and Q18 were normally coded (Strongly disagree = 0, Somewhat disagree = 1, Neither agree nor disagree = 2, Somewhat agree = 3, Strongly agree = 4), while questions Q2, Q4, Q6, Q14, Q16, and Q17 were reverse-coded (Strongly disagree = 4, Somewhat disagree = 3, Neither agree nor disagree = 2, Somewhat agree = 1, Strongly agree = 0).</p>
<p>Reverse coding was necessary because some survey items were phrased in the opposite direction. For example, Q1 asks “I dislike participating in group discussions” (normal coded), where agreement indicates higher communication apprehension. In contrast, Q2 asks “Generally, I am comfortable while participating in group discussions” (reverse coded), where agreement indicates lower communication apprehension. Without reverse coding, these items would be scored in opposite directions, leading to inconsistent measurement. By reverse-coding Q2 (and similar items), we ensure that higher scores consistently represent higher communication apprehension across all items.</p>
<p>Transportation usage variables were created from survey questions Q26 (public transportation) and Q28 (ride-share). Binary variables indicated whether participants used each mode (Never = 0, any use = 1). Frequency variables were created with ordinal coding: Never = 0, 0-1 days a month = 1, 2-4 days a month = 2, 4-8 days a month = 3, 8 or more days a month = 4. Daily frequency variables were similarly coded for typical daily usage patterns.</p>
<p>A composite communication apprehension score was calculated by summing responses to the 12 communication apprehension questions (Q1-Q6 and Q13-Q18) and dividing by 5, resulting in a score representing average communication apprehension per question. Finally, a minimal dataset was created containing only the essential variables for analysis: participant ID, age, sex, transportation usage variables, and the communication apprehension score.</p>
</section>
</section>
<section id="transportation-habits-and-communication-apprehension" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Transportation Habits and Communication Apprehension</h1>
<section id="transportation-mode-differences" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="transportation-mode-differences"><span class="header-section-number">3.1</span> Transportation Mode Differences</h2>
<p>We first examined whether communication apprehension differed based on transportation mode usage. Participants were categorized into four groups based on their transportation habits: those who used neither ride-share nor public transportation, those who used only public transportation, those who used only ride-share, and those who used both modes.</p>
<div class="cell">
<div id="tbl-transport-groups" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-transport-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Average communication apprehension by transportation group
</figcaption>
<div aria-describedby="tbl-transport-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 30%">
<col style="width: 63%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Transportation group</th>
<th style="text-align: right;">Mean communication apprehension per Question</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Neither</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ride share only</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Public transport only</td>
<td style="text-align: right;">1.59</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="even">
<td style="text-align: left;">Both</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">165</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As shown in <a href="#tbl-transport-groups" class="quarto-xref">Table&nbsp;1</a>, ride-share-only users had the lowest average communication apprehension scores (1.17), followed by those who used both modes (1.23), public transportation-only users (1.59), and those who used neither mode (2.11). This pattern suggests that transportation mode is associated with communication apprehension, with ride-share users showing particularly low levels.</p>
</section>
<section id="transportation-frequency-effects" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="transportation-frequency-effects"><span class="header-section-number">3.2</span> Transportation Frequency Effects</h2>
<p>Beyond simple mode usage, we examined whether the frequency of transportation use was associated with communication apprehension. We conducted a linear regression analysis including both ride-share frequency and public transportation frequency as predictors of communication apprehension.</p>
<p>The analysis revealed that each one-category increase in ride-share frequency was associated with an average 0.23-point decrease in communication apprehension, accounting for public-transport frequency, <em>b</em> = −0.23, <em>SE</em> = 0.05, <em>t</em>(249) = −4.28, <em>p</em> &lt; .001. In contrast, each one-category increase in public-transport frequency was associated with an estimated 0.05-point decrease in communication apprehension after accounting for ride-share frequency; however, this association was not statistically significant, <em>b</em> = −0.05, <em>SE</em> = 0.05, <em>t</em>(249) = −1.00, <em>p</em> = .318.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-transport-frequency" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-transport-frequency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GroupManu_files/figure-html/fig-transport-frequency-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-transport-frequency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Relationship between transportation-use frequency and communication apprehension
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-transport-frequency" class="quarto-xref">Figure&nbsp;1</a> helps visualize this pattern: the black line shows the overall negative relationship between transportation-use frequency and communication apprehension, while the colored lines show the trends among ride-share-only and public-transportation-only users. The ride-share group shows a more pronounced decrease in communication apprehension as frequency increases, while the trend among public-transportation-only users is weaker.</p>
<p>Additional analysis using ANOVA confirmed that communication apprehension differed significantly across rideshare frequency groups, <em>F</em>(4, 255) = 9.31, <em>p</em> &lt; .001, with Tukey post-hoc tests showing that participants who used rideshare 2–4 days per month, 4–8 days per month, or 8 or more days per month had significantly lower communication apprehension than participants who never used rideshare. In contrast, no significant differences were found across public transportation frequency groups, <em>F</em>(4, 255) = 1.23, <em>p</em> = .30.</p>
</section>
</section>
<section id="age-and-communication-apprehension" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Age and Communication Apprehension</h1>
<p>We next examined whether age was associated with communication apprehension. Given the mixed findings in the literature regarding age and communication anxiety, we tested this relationship using both correlation and regression analyses.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-age-ca" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-age-ca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GroupManu_files/figure-html/fig-age-ca-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-age-ca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Relationship between age and communication apprehension
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-age-ca" class="quarto-xref">Figure&nbsp;2</a>, the scatterplot revealed a slight downward trend, but scores varied widely across ages. A Pearson correlation found a weak negative relationship between age and communication apprehension, <em>r</em> = -0.101, <em>p</em> = 0.108. Linear regression analysis confirmed this weak relationship, <em>b</em> = -0.007, <em>SE</em> = 0.004, <em>t</em>(250) = -1.61, <em>p</em> = 0.108. Age explained only 1.0% of the variation in communication apprehension, indicating that age was not a significant predictor of communication apprehension in this sample.</p>
</section>
<section id="interaction-between-transportation-use-and-age" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Interaction Between Transportation Use and Age</h1>
<p>Given that transportation habits—particularly ride-share usage—showed a significant association with communication apprehension while age did not, we tested whether age moderates the relationship between transportation use and communication apprehension. Specifically, we hypothesized that the negative effect of transportation use on communication apprehension would be more pronounced in younger participants than in older participants.</p>
<section id="age-group-moderation-analysis" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="age-group-moderation-analysis"><span class="header-section-number">5.1</span> Age Group Moderation Analysis</h2>
<p>Participants were categorized into two age groups: young (ages 17-30) and old (ages 31+). We created an overall transportation frequency score by summing ride-share and public transportation monthly frequency values, then tested whether this overall transportation frequency interacted with age group in predicting communication apprehension.</p>
<p>The moderation analysis revealed a significant interaction between overall transportation frequency and age group, supporting our hypothesis. The overall model was significant, <em>F</em>(3, 248) = 17.91, <em>p</em> &lt; .001, <em>R</em>² = .178. The interaction term between overall transportation frequency and age group was statistically significant, <em>b</em> = 0.12, <em>SE</em> = 0.05, <em>t</em>(248) = 2.20, <em>p</em> = .029, indicating that the relationship between transportation use and communication apprehension differs between young and old participants.</p>
<p>For young participants, each one-unit increase in overall transportation frequency was associated with a 0.24-point decrease in communication apprehension, <em>b</em> = −0.24, <em>SE</em> = 0.05, <em>t</em>(248) = −5.24, <em>p</em> &lt; .001. In contrast, for old participants, the effect of transportation frequency was weaker (the simple slope was −0.24 + 0.12 = −0.12), and this difference in slopes was statistically significant as indicated by the interaction term.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-moderation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-moderation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GroupManu_files/figure-html/fig-moderation-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-moderation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Interaction between overall transportation frequency and age group in predicting communication apprehension
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-moderation" class="quarto-xref">Figure&nbsp;3</a>, the negative relationship between overall transportation frequency and communication apprehension is steeper for young participants compared to old participants. This supports our hypothesis that transportation use has a more pronounced effect on communication apprehension among younger individuals.</p>
<p>When we examined ride-share and public transportation frequencies separately in a model including both modes and their interactions with age group, the specific mode-by-age interactions were not statistically significant. This suggests that the moderation effect is driven by overall transportation use rather than specific transportation modes.</p>
</section>
</section>
<section id="predictive-modeling" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Predictive Modeling</h1>
<p>Beyond traditional linear regression approaches, we explored machine learning techniques to predict communication apprehension using transportation habits and age as predictors. These models may capture non-linear relationships and complex interactions that traditional regression might miss. All models used the same predictors: age, public_transport_monthly, public_transport_daily, ride_share_monthly, ride_share_daily, and transport_group.</p>
<section id="baseline-model" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="baseline-model"><span class="header-section-number">6.1</span> Baseline Model</h2>
<p>As a simple baseline, we calculated the mean communication apprehension score from the training set and used this value to predict all observations in the validation set. This provides a minimum standard for model performance.</p>
<p>The baseline model achieved an RMSE of 1.09, representing the error when simply predicting the average communication apprehension for all participants.</p>
</section>
<section id="k-nearest-neighbors-knn" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="k-nearest-neighbors-knn"><span class="header-section-number">6.2</span> K-Nearest Neighbors (KNN)</h2>
<p>K-Nearest Neighbors is a non-parametric method that predicts values based on the k most similar training examples. We implemented KNN regression with k=5 neighbors. The data were split into training (80%) and validation (20%) sets. Predictors were converted to numeric, dummy variables were created for transport_group, missing values were imputed using median values, and all numeric predictors were scaled to have comparable ranges.</p>
<p>The KNN model achieved an RMSE of 1.06 on the validation set, showing a modest improvement over the baseline model.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-knn-concept" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-knn-concept-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GroupManu_files/figure-html/fig-knn-concept-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-knn-concept-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Conceptual illustration of KNN prediction
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="random-forest" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="random-forest"><span class="header-section-number">6.3</span> Random Forest</h2>
<p>Random Forest is an ensemble learning method that constructs multiple decision trees and combines their predictions. We used 100 trees with hyperparameters tuned via 5-fold cross-validation on the training set. The tuning grid explored mtry values (2-6) and minimum node size parameters. The same preprocessing as KNN was applied (numeric conversion, dummy variables, median imputation), but scaling was not required for tree-based methods.</p>
<p>The Random Forest model achieved an RMSE of 0.90 on the validation set, representing a substantial improvement over both the baseline and KNN models. This suggests that the ensemble approach captured important patterns in the data that simpler methods missed.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rf-importance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rf-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GroupManu_files/figure-html/fig-rf-importance-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rf-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Variable importance from Random Forest model
</figcaption>
</figure>
</div>
</div>
</div>
<p>As shown in <a href="#fig-rf-importance" class="quarto-xref">Figure&nbsp;5</a>, age and ride-share monthly frequency were the most important predictors in the Random Forest model, followed by public transportation monthly frequency.</p>
</section>
<section id="neural-networks" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="neural-networks"><span class="header-section-number">6.4</span> Neural Networks</h2>
<p>Neural networks are flexible models capable of learning complex, non-linear relationships. We implemented a feedforward neural network using the brulee engine. The data were split into training (60%), validation (20%), and test (20%) sets to properly evaluate hyperparameter selection. Hyperparameters were tuned via 5-fold cross-validation on the training set, exploring hidden units (2, 5, 10), activation functions (relu, tanh, sigmoid), and penalty values (0.0001, 0.001, 0.01, 0.1). The final model was fit on combined training and validation data with the best hyperparameters and evaluated on the held-out test set.</p>
<p>The Neural Network achieved an RMSE of 0.87 on the test set, representing the best performance among all models tested. This suggests that the neural network captured subtle patterns in the data that even the Random Forest missed.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-nn-architecture" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nn-architecture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GroupManu_files/figure-html/fig-nn-architecture-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nn-architecture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Architecture of the final neural network model
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="model-comparison" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="model-comparison"><span class="header-section-number">6.5</span> Model Comparison</h2>
<div class="cell">
<div id="tbl-model-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Model performance comparison (RMSE)
</figcaption>
<div aria-describedby="tbl-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Baseline (mean)</td>
<td style="text-align: right;">1.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">KNN (k=5)</td>
<td style="text-align: right;">1.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: right;">0.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">Neural Network</td>
<td style="text-align: right;">0.87</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As shown in <a href="#tbl-model-comparison" class="quarto-xref">Table&nbsp;2</a>, all machine learning models outperformed the baseline, with the Neural Network achieving the lowest RMSE (0.87), followed by Random Forest (0.90), and KNN (1.06). The improvement over baseline suggests that transportation habits and age contain meaningful predictive information about communication apprehension.</p>
</section>
<section id="prediction-accuracy-visualizations" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="prediction-accuracy-visualizations"><span class="header-section-number">6.6</span> Prediction Accuracy Visualizations</h2>
<div class="cell">
<div id="fig-predictions" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="fig-predictions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="GroupManu_files/figure-html/fig-predictions-1.png" class="img-fluid figure-img" style="width:120.0%" data-ref-parent="fig-predictions">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) KNN
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Model predictions vs actual communication apprehension
</figcaption>
</figure>
</div>
</div>
<p><a href="#fig-predictions" class="quarto-xref">Figure&nbsp;7</a> shows the predicted versus actual communication apprehension values for each model. Points closer to the diagonal red line indicate better predictions. The Neural Network plot demonstrates that the best model actually constrained its predictions to a narrower range in order to minimize error.</p>
</section>
</section>
<section id="conclusion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion</h1>
<p>This study examined the relationships between transportation habits, age, and communication apprehension. Our analyses revealed that transportation habits—particularly ride-share usage—are significantly associated with communication apprehension, with more frequent ride-share users reporting lower communication apprehension. In contrast, public transportation frequency showed no significant association with communication apprehension after accounting for ride-share usage. Age was not a significant predictor of communication apprehension in this sample.</p>
<p>Importantly, we found a significant interaction between overall transportation frequency and age group, supporting our hypothesis that transportation use has a more pronounced effect on communication apprehension among younger participants (ages 17-30) compared to older participants (ages 31+). For young participants, each one-unit increase in overall transportation frequency was associated with a 0.24-point decrease in communication apprehension, whereas the effect was weaker for older participants.</p>
<p>These findings suggest that the mode and frequency of transportation use may be more relevant to communication apprehension than demographic factors like age. The stronger association for ride-share compared to public transportation may reflect differences in the social interaction requirements of these transportation modes. The moderation by age suggests that younger adults may be more sensitive to the social and psychological aspects of transportation experiences.</p>
<p>Predictive modeling analyses demonstrated that machine learning approaches can predict communication apprehension from transportation habits and age with reasonable accuracy. All models outperformed a simple baseline that predicted the mean, with the Neural Network achieving the best performance (RMSE = 0.87), followed by Random Forest (RMSE = 0.90), and KNN (RMSE = 1.06). This suggests that transportation habits and age contain meaningful predictive information about communication apprehension, and that complex non-linear relationships exist that can be captured by machine learning methods.</p>
<section id="remaining-questions" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="remaining-questions"><span class="header-section-number">7.1</span> Remaining Questions</h2>
<p>Several questions remain for future investigation. First, the difference between the ride-share and public transportation relationships has not been directly tested for statistical significance. Second, other factors such as employment status, education, and geographic location may moderate these relationships and warrant further investigation. Third, the neural network model, while achieving the best performance, is less interpretable than simpler models; future work could explore model interpretability techniques to understand which specific patterns the neural network captured. Finally, the sample size for this study was relatively modest; replication with larger samples would strengthen confidence in these findings.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>