<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Com_Apprehension_Transportation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Communication_Apprehension_Transportation_Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Communication_Apprehension_Transportation_Analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Communication_Apprehension_Transportation_Analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Communication_Apprehension_Transportation_Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Communication_Apprehension_Transportation_Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Communication_Apprehension_Transportation_Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Communication_Apprehension_Transportation_Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Communication_Apprehension_Transportation_Analysis_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Communication_Apprehension_Transportation_Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Communication_Apprehension_Transportation_Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Communication_Apprehension_Transportation_Analysis_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Com_Apprehension_Transportation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="preparation" class="level1">
<h1>Preparation</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">conflicts.policy =</span> <span class="st">"depends.ok"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>path_data <span class="ot">&lt;-</span> <span class="st">"groupproject_sibling_data/cleandata"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(here<span class="sc">::</span><span class="fu">here</span>(path_data, <span class="st">"minimal_clean.csv"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 252
Columns: 11
$ ResponseId                     &lt;chr&gt; "1cab4557741ee763d960a629350156b8590462…
$ Age                            &lt;dbl&gt; 39, 61, 31, 35, 52, 42, 30, 48, 45, 42,…
$ Sex                            &lt;chr&gt; "Male", "Male", "Male", "Female", "Male…
$ public_transport               &lt;int&gt; 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, …
$ public_transport_monthly       &lt;int&gt; 0, 0, 0, 2, 4, 0, 0, 1, 0, 1, 4, 0, 4, …
$ public_transport_daily         &lt;dbl&gt; 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, …
$ ride_share                     &lt;int&gt; 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, …
$ ride_share_monthly             &lt;int&gt; 0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2, 0, 4, …
$ ride_share_daily               &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ raw_communication_apprehension &lt;dbl&gt; 11, 4, 27, 18, 12, 36, 21, 4, 8, 12, 30…
$ communication_apprehension     &lt;dbl&gt; 0.9166667, 0.3333333, 2.2500000, 1.5000…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="fu">as.integer</span>(Age),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sex =</span> <span class="fu">factor</span>(Sex),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">public_transport =</span> <span class="fu">factor</span>(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>      public_transport,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">public_transport_monthly =</span> <span class="fu">ordered</span>(</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>      public_transport_monthly,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">public_transport_daily =</span> <span class="fu">ordered</span>(</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>      public_transport_daily,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">ride_share =</span> <span class="fu">factor</span>(</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>      ride_share,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">ride_share_monthly =</span> <span class="fu">ordered</span>(</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>      ride_share_monthly,</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">ride_share_daily =</span> <span class="fu">ordered</span>(</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>      ride_share_daily,</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 252
Columns: 11
$ ResponseId                     &lt;chr&gt; "1cab4557741ee763d960a629350156b8590462…
$ Age                            &lt;int&gt; 39, 61, 31, 35, 52, 42, 30, 48, 45, 42,…
$ Sex                            &lt;fct&gt; Male, Male, Male, Female, Male, Male, M…
$ public_transport               &lt;fct&gt; 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, …
$ public_transport_monthly       &lt;ord&gt; 0, 0, 0, 2, 4, 0, 0, 1, 0, 1, 4, 0, 4, …
$ public_transport_daily         &lt;ord&gt; 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, …
$ ride_share                     &lt;fct&gt; 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, …
$ ride_share_monthly             &lt;ord&gt; 0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2, 0, 4, …
$ ride_share_daily               &lt;ord&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ raw_communication_apprehension &lt;dbl&gt; 11, 4, 27, 18, 12, 36, 21, 4, 8, 12, 30…
$ communication_apprehension     &lt;dbl&gt; 0.9166667, 0.3333333, 2.2500000, 1.5000…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> data_all <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">transport_group =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>      ride_share <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> public_transport <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Neither"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>      ride_share <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> public_transport <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Ride share only"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>      ride_share <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> public_transport <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Public transport only"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>      ride_share <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> public_transport <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Both"</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">transport_group =</span> <span class="fu">factor</span>(</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>      transport_group,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Neither"</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Ride share only"</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Public transport only"</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Both"</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="ride-share-users-vs-non-users" class="level3">
<h3 class="anchored" data-anchor-id="ride-share-users-vs-non-users">Ride-share users vs non-users</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ride_share_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> ride_share,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ride_share_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ ride_share, data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.5185 -0.6553 -0.2287  0.6046  2.5213 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   1.8519     0.1062  17.435  &lt; 2e-16 ***
ride_share1  -0.6231     0.1257  -4.958 1.31e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9013 on 250 degrees of freedom
Multiple R-squared:  0.08954,   Adjusted R-squared:  0.08589 
F-statistic: 24.59 on 1 and 250 DF,  p-value: 1.313e-06</code></pre>
</div>
</div>
<p>Ride-share users had communication apprehension scores that were, on average, 0.62 points lower (per question) than those of non-users, <em>b</em> = −0.62, <em>SE</em> = 0.13, <em>t</em>(250) = −4.96, <em>p</em> &lt; .001.</p>
</section>
<section id="public-transport-users-vs-non-users" class="level3">
<h3 class="anchored" data-anchor-id="public-transport-users-vs-non-users">Public transport users vs non-users</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>public_transport_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> public_transport,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(public_transport_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ public_transport, data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.8333 -0.6318 -0.2152  0.6182  2.4515 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         1.8333     0.1288  14.238  &lt; 2e-16 ***
public_transport1  -0.5348     0.1442  -3.709 0.000256 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9196 on 250 degrees of freedom
Multiple R-squared:  0.05217,   Adjusted R-squared:  0.04838 
F-statistic: 13.76 on 1 and 250 DF,  p-value: 0.000256</code></pre>
</div>
</div>
<p>Public transportation users had communication apprehension scores that were, on average, 0.53 points lower (per question) than those of non-users, <em>b</em> = −0.53, <em>SE</em> = 0.14, <em>t</em>(250) = −3.71, <em>p</em> &lt; .001.</p>
</section>
<section id="both-there-is-overlap" class="level3">
<h3 class="anchored" data-anchor-id="both-there-is-overlap">Both (there is overlap)</h3>
<p>Some participants use both public transportation and ride-shares, so this model doesn’t directly answer our question.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>transport_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> ride_share <span class="sc">+</span> public_transport,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(transport_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ ride_share + public_transport, 
    data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6508 -0.6380 -0.2066  0.6267  2.5434 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         1.9842     0.1325  14.976  &lt; 2e-16 ***
ride_share1        -0.5129     0.1418  -3.618 0.000359 ***
public_transport1  -0.2647     0.1594  -1.660 0.098091 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8981 on 249 degrees of freedom
Multiple R-squared:  0.09951,   Adjusted R-squared:  0.09227 
F-statistic: 13.76 on 2 and 249 DF,  p-value: 2.152e-06</code></pre>
</div>
</div>
<p>Ride-share users who did not use public transportation had estimated communication apprehension scores 0.51 points lower, on average, than participants who used neither mode, <em>b</em> = −0.51, <em>SE</em> = 0.14, <em>t</em>(249) = −3.62, <em>p</em> &lt; .001.</p>
<p>Public-transport users who did not use ride share had estimated communication apprehension scores 0.26 points lower, on average, than participants who used neither mode, <em>b</em> = −0.26, <em>SE</em> = 0.16, <em>t</em>(249) = −1.66, <em>p</em> = .098.</p>
<table class="caption-top table">
<caption>*Public Transportation value uses ALL Ps who use public transport (including those that also use ride-share). Likewise, Ride Share Transportation value uses ALL Ps who use ride-share (including those that also use public transportation).</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Transportation</th>
<th style="text-align: center;">Avg. Communication Apprehension/Question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Neither</td>
<td style="text-align: center;">1.98</td>
</tr>
<tr class="even">
<td style="text-align: center;">Public Transportation</td>
<td style="text-align: center;">1.72</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ride Share</td>
<td style="text-align: center;">1.47</td>
</tr>
<tr class="even">
<td style="text-align: center;">Public Transport &amp; Ride Share</td>
<td style="text-align: center;">1.21</td>
</tr>
</tbody>
</table>
</section>
<section id="both-using-groups-to-isolate" class="level3">
<h3 class="anchored" data-anchor-id="both-using-groups-to-isolate">Both, using groups to isolate</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>transport_group_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> transport_group,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(transport_group_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ transport_group, data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7778 -0.6211 -0.1635  0.6667  2.5157 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                            2.1111     0.1490  14.170  &lt; 2e-16 ***
transport_groupRide share only        -0.9444     0.2747  -3.438 0.000687 ***
transport_groupPublic transport only  -0.5185     0.2107  -2.461 0.014538 *  
transport_groupBoth                   -0.8768     0.1644  -5.332 2.19e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8939 on 248 degrees of freedom
Multiple R-squared:  0.1115,    Adjusted R-squared:  0.1008 
F-statistic: 10.38 on 3 and 248 DF,  p-value: 1.862e-06</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Transportation</th>
<th style="text-align: center;">Avg. Communication Apprehension/Question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Neither</td>
<td style="text-align: center;">2.11</td>
</tr>
<tr class="even">
<td style="text-align: center;">Public Transportation Only</td>
<td style="text-align: center;">1.59</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ride Share Only</td>
<td style="text-align: center;">1.17</td>
</tr>
<tr class="even">
<td style="text-align: center;">Public Transport &amp; Ride Share</td>
<td style="text-align: center;">1.23</td>
</tr>
</tbody>
</table>
<p><strong>Ride share only vs.&nbsp;neither:</strong></p>
<p>Participants who used ride share but not public transportation reported communication apprehension scores that were, on average, <strong>0.94 points lower</strong> than participants who used neither mode, <em>b</em> = −0.94, <em>SE</em> = 0.27, <em>t</em>(248) = −3.44, <em>p</em> &lt; .001.</p>
<p><strong>Public transport only vs.&nbsp;neither:</strong></p>
<p>Participants who used public transportation but not ride share reported communication apprehension scores that were, on average, <strong>0.52 points lower</strong> than participants who used neither mode, <em>b</em> = −0.52, <em>SE</em> = 0.21, <em>t</em>(248) = −2.46, <em>p</em> = .015.</p>
<p><strong>Both vs.&nbsp;neither:</strong></p>
<p>Participants who used both ride share and public transportation reported communication apprehension scores that were, on average, <strong>0.88 points lower</strong> than participants who used neither mode, <em>b</em> = −0.88, <em>SE</em> = 0.16, <em>t</em>(248) = −5.33, <em>p</em> &lt; .001.</p>
<p><strong>Overall model is significant:</strong></p>
<p>Transportation-use group was significantly associated with communication apprehension, <em>F</em>(3, 248) = 10.38, <em>p</em> &lt; .001, Rsqu = .112, so ~11.2% of the variance in communication apprehension is accounted for by which transportation group one falls into.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> data_all <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">transport_group =</span> <span class="fu">relevel</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>      transport_group,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">ref =</span> <span class="st">"Public transport only"</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>model_group <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> transport_group,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_group)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ transport_group, data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7778 -0.6211 -0.1635  0.6667  2.5157 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      1.5926     0.1490  10.690   &lt;2e-16 ***
transport_groupNeither           0.5185     0.2107   2.461   0.0145 *  
transport_groupRide share only  -0.4259     0.2747  -1.550   0.1223    
transport_groupBoth             -0.3582     0.1644  -2.179   0.0303 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8939 on 248 degrees of freedom
Multiple R-squared:  0.1115,    Adjusted R-squared:  0.1008 
F-statistic: 10.38 on 3 and 248 DF,  p-value: 1.862e-06</code></pre>
</div>
</div>
<p>Using public transport only as our reference group, we now have a test statistic that directly compares public transport only to ride share only.</p>
<p>Participants who use ride share but not public transportation had communication apprehension scores that were, on average, 0.43 points lower than participants who use public transportation but not ride share; however, this difference was not statistically significant, <em>b</em> = −0.43, <em>SE</em> = 0.27, <em>t</em>(248) = −1.55, <em>p</em> = .122.</p>
<p><strong>Maybe more interesting question: Do Ps who use ride-share, public transport, or both differ in communication apprehension from people who use neither?</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> data_all <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">any_transport =</span> <span class="fu">case_when</span>(</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>      ride_share <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> public_transport <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Neither"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>      ride_share <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> public_transport <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Any"</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">any_transport =</span> <span class="fu">factor</span>(</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>      any_transport,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Neither"</span>, <span class="st">"Any"</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>model_any <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> any_transport,</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_any)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ any_transport, data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7778 -0.6227 -0.2060  0.6273  2.4606 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        2.1111     0.1499  14.084  &lt; 2e-16 ***
any_transportAny  -0.8218     0.1619  -5.076 7.54e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8993 on 250 degrees of freedom
Multiple R-squared:  0.09342,   Adjusted R-squared:  0.0898 
F-statistic: 25.76 on 1 and 250 DF,  p-value: 7.543e-07</code></pre>
</div>
</div>
<p>Participants who used either ride share, public transportation, or both reported communication apprehension scores that were, on average, 0.82 points lower than participants who used neither mode, <em>b</em> = −0.82, <em>SE</em> = 0.16, <em>t</em>(250) = −5.08, <em>p</em> &lt; .001.</p>
</section>
<section id="analysis-including-frequency-of-use." class="level3">
<h3 class="anchored" data-anchor-id="analysis-including-frequency-of-use.">Analysis including frequency of use.</h3>
<p>Probably going to only use monthly since the daily question didn’t give participants the option to choose 0 even if they reported never using that mode of transport.</p>
<section id="quick-eda" class="level4">
<h4 class="anchored" data-anchor-id="quick-eda">Quick EDA</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ride_share_monthly) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_CA =</span> <span class="fu">mean</span>(communication_apprehension, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_CA =</span> <span class="fu">sd</span>(communication_apprehension, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  ride_share_monthly     n mean_CA sd_CA
  &lt;ord&gt;              &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 0                     72    1.85 0.997
2 1                     49    1.59 0.998
3 2                     70    1.16 0.778
4 3                     43    1.03 0.808
5 4                     18    1.01 0.606</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(public_transport_monthly) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_CA =</span> <span class="fu">mean</span>(communication_apprehension, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_CA =</span> <span class="fu">sd</span>(communication_apprehension, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  public_transport_monthly     n mean_CA sd_CA
  &lt;ord&gt;                    &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 0                           51    1.83 1.11 
2 1                           40    1.51 0.890
3 2                           54    1.33 0.923
4 3                           51    1.24 0.764
5 4                           56    1.17 0.868</code></pre>
</div>
</div>
</section>
<section id="analysis-1" class="level4">
<h4 class="anchored" data-anchor-id="analysis-1">Analysis</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model_ride_frequency <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> <span class="fu">factor</span>(ride_share_monthly),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>model_public_frequency <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> <span class="fu">factor</span>(public_transport_monthly),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_ride_frequency)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ factor(ride_share_monthly), 
    data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.5867 -0.6759 -0.1583  0.5648  2.7229 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   1.32666    0.06324  20.979  &lt; 2e-16 ***
factor(ride_share_monthly).L -0.70986    0.15882  -4.470  1.2e-05 ***
factor(ride_share_monthly).Q  0.21159    0.14567   1.452    0.148    
factor(ride_share_monthly).C  0.08747    0.13840   0.632    0.528    
factor(ride_share_monthly)^4 -0.07702    0.11990  -0.642    0.521    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8859 on 247 degrees of freedom
Multiple R-squared:  0.131, Adjusted R-squared:  0.1169 
F-statistic: 9.306 on 4 and 247 DF,  p-value: 5.078e-07</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_public_frequency)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ factor(public_transport_monthly), 
    data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.8333 -0.6651 -0.1626  0.5861  2.5819 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         1.4165985  0.0582817  24.306  &lt; 2e-16 ***
factor(public_transport_monthly).L -0.5037961  0.1281286  -3.932 0.000109 ***
factor(public_transport_monthly).Q  0.1575991  0.1272518   1.238 0.216713    
factor(public_transport_monthly).C -0.0441475  0.1350034  -0.327 0.743937    
factor(public_transport_monthly)^4 -0.0007921  0.1307643  -0.006 0.995172    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9188 on 247 degrees of freedom
Multiple R-squared:  0.06513,   Adjusted R-squared:  0.04999 
F-statistic: 4.302 on 4 and 247 DF,  p-value: 0.002208</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_ride_frequency)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: communication_apprehension
                            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
factor(ride_share_monthly)   4  29.212  7.3030  9.3062 5.078e-07 ***
Residuals                  247 193.833  0.7847                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_public_frequency)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: communication_apprehension
                                  Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
factor(public_transport_monthly)   4  14.528  3.6320  4.3023 0.002208 **
Residuals                        247 208.517  0.8442                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Overall model</strong></p>
<p>Communication apprehension differed significantly across levels of monthly ride-share use, <em>F</em>(4, 247) = 9.31, <em>p</em> &lt; .001, Rsqu = .131</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model_frequency_both <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">factor</span>(ride_share_monthly) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">factor</span>(public_transport_monthly),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_frequency_both)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ factor(ride_share_monthly) + 
    factor(public_transport_monthly), data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7425 -0.6778 -0.1591  0.5561  2.7527 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         1.33570    0.06609  20.209  &lt; 2e-16 ***
factor(ride_share_monthly).L       -0.64379    0.18555  -3.470 0.000617 ***
factor(ride_share_monthly).Q        0.17563    0.15408   1.140 0.255472    
factor(ride_share_monthly).C        0.09891    0.14112   0.701 0.484067    
factor(ride_share_monthly)^4       -0.07328    0.12095  -0.606 0.545176    
factor(public_transport_monthly).L -0.12946    0.15046  -0.860 0.390407    
factor(public_transport_monthly).Q  0.09286    0.13044   0.712 0.477216    
factor(public_transport_monthly).C -0.07775    0.13313  -0.584 0.559725    
factor(public_transport_monthly)^4 -0.02953    0.12724  -0.232 0.816654    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8901 on 243 degrees of freedom
Multiple R-squared:  0.1369,    Adjusted R-squared:  0.1085 
F-statistic: 4.819 on 8 and 243 DF,  p-value: 1.603e-05</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_frequency_both)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: communication_apprehension
                                  Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
factor(ride_share_monthly)         4  29.212  7.3030  9.2186 5.967e-07 ***
factor(public_transport_monthly)   4   1.327  0.3318  0.4189     0.795    
Residuals                        243 192.505  0.7922                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>There was a significant negative linear trend in communication apprehension across increasing categories of ride-share frequency, after controlling for public-transport frequency, <em>b</em> = −0.64, <em>SE</em> = 0.19, <em>t</em>(243) = −3.47, <em>p</em> &lt; .001.</p>
<p>i.e.&nbsp;<strong>Ps tended to have lower communication apprehension as ride-share use increased, even after accounting for differences in public transportation use.</strong></p>
<p>AND</p>
<p>There was no evidence of a linear trend in communication apprehension across increasing categories of public-transport frequency after controlling for ride-share frequency, <em>b</em> = −0.13, <em>SE</em> = 0.15, <em>t</em>(243) = −0.86, <em>p</em> = .390.</p>
<p>i.e.&nbsp;<strong>After accounting for ride-share frequency, public transportation frequency was not significantly associated with communication apprehension.</strong></p>
</section>
<section id="analysis-treating-frequency-categories-as-numeric-rather-than-ordinal" class="level4">
<h4 class="anchored" data-anchor-id="analysis-treating-frequency-categories-as-numeric-rather-than-ordinal">Analysis treating frequency categories as numeric rather than ordinal</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> data_all <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ride_frequency =</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(ride_share_monthly)),</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">public_frequency =</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(public_transport_monthly))</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>model_frequency <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  communication_apprehension <span class="sc">~</span> ride_frequency <span class="sc">+</span> public_frequency,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_all</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_frequency)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = communication_apprehension ~ ride_frequency + public_frequency, 
    data = data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6300 -0.7063 -0.1663  0.5651  2.7656 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       1.85870    0.10238  18.155  &lt; 2e-16 ***
ride_frequency   -0.22868    0.05341  -4.282 2.65e-05 ***
public_frequency -0.04706    0.04699  -1.001    0.318    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.886 on 249 degrees of freedom
Multiple R-squared:  0.1236,    Adjusted R-squared:  0.1165 
F-statistic: 17.56 on 2 and 249 DF,  p-value: 7.373e-08</code></pre>
</div>
</div>
<p><strong>Each one-category increase in ride-share frequency was associated with an average 0.23-point decrease in communication apprehension, accounting for public-transport frequency, <em>b</em> = −0.23, <em>SE</em> = 0.05, <em>t</em>(249) = −4.28, <em>p</em> &lt; .001.</strong></p>
<p><strong>Each one-category increase in public-transport frequency was associated with an estimated 0.05-point decrease in communication apprehension after accounting for ride-share frequency; however, this association was not statistically significant, <em>b</em> = −0.05, <em>SE</em> = 0.05, <em>t</em>(249) = −1.00, <em>p</em> = .318.</strong></p>
</section>
<section id="visualization" class="level4">
<h4 class="anchored" data-anchor-id="visualization">Visualization</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> data_all <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    communication_apprehension,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    ride_share_monthly,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    public_transport_monthly</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(ride_share_monthly, public_transport_monthly),</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"transport"</span>,</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"frequency"</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">frequency =</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(frequency))</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>  plot_data,</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> frequency,</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> communication_apprehension,</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> transport</span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">height =</span> <span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-27"><a href="#cb48-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Monthly use frequency"</span>,</span>
<span id="cb48-28"><a href="#cb48-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Communication apprehension"</span>,</span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Transportation mode"</span></span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-31"><a href="#cb48-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Communication_Apprehension_Transportation_Analysis_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>exclusive_plot <span class="ot">&lt;-</span> data_all <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>    transport_group <span class="sc">%in%</span> <span class="fu">c</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Ride share only"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Public transport only"</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">frequency =</span> <span class="fu">if_else</span>(</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>      transport_group <span class="sc">==</span> <span class="st">"Ride share only"</span>,</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(ride_share_monthly)),</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(public_transport_monthly))</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>  exclusive_plot,</span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> frequency,</span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> communication_apprehension,</span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> transport_group</span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">height =</span> <span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Monthly use frequency"</span>,</span>
<span id="cb50-28"><a href="#cb50-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Communication apprehension"</span>,</span>
<span id="cb50-29"><a href="#cb50-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Transportation mode"</span></span>
<span id="cb50-30"><a href="#cb50-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb50-31"><a href="#cb50-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Communication_Apprehension_Transportation_Analysis_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>